#
###################################
# Site wide configuration
####################################
#
title: Jason
email: jiang-xun@qq.com
description: Jason's blog.
url: https://developerjx.github.io # the base hostname & protocol for your site
lang: zh-CN

#
###################################
# Jekyll configuration
####################################
#
markdown:           kramdown
highlighter:        rouge
excerpt_separator:  <!--more-->
timezone:          Asia/Taipei

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jason
  avatar: logo.png
  job: "iOS Developer"
  bio_chinese: "一个追求性能与高质量用户体验的中国iOS开发攻城狮"
  bio: "A high-quality performance and user experience of suitor,China."
  email: jiang-xun@qq.com
  disqus-shortname: jasonblog
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-74439815-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: developerjx #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
