#
###################################
# Site wide configuration
####################################
#
title: Jx
email: jiang-xun@qq.com
description: Jx's blog.
url: https://developerjx.github.io # the base hostname & protocol for your site
lang: zh-CN

#
###################################
# Jekyll configuration
####################################
#
markdown:           kramdown
highlighter:        rouge
excerpt_separator:  <!--more-->
timezone:           Europe/Paris

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jx
  avatar: logo.png
  job: "iOS Developer"
  bio: "A backend developer who loves design awesome things. Working for RendezvousCheznous atm in Marseille, China!"
  email: jiang-xun@qq.com
  disqus-shortname: jxblog
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: developerjx #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
